Remove NEW_FILE_CREATION file on exit (#4)
Fix #3

diff --git a/fzf-notes b/fzf-notes
--- a/fzf-notes
+++ b/fzf-notes
@@ -6,6 +6,8 @@
 # A script for quickly editing your notes. Allows creation of new files by
 # selecting CREATE_NEW_FILE at the menu.
 
+# Depends on GNU getopt
+
 # Exit on error
 set -e
 
@@ -21,14 +23,17 @@ function touch_create_parent() {
 	mkdir -p "$(dirname "$1")" && touch "$1"
 }
 
-# Trims leading and trailing whitespace from argument
+# Trims leading and trailing whitespace from argument, and removes trailing slashes
 function trim() {
 	shopt -s extglob
 	input="$1"
+	# Strip leading whitespace
 	input="${input##*( )}"
+	# Strip trailing whitespace
 	input="${input%%*( )}"
 	shopt -u extglob
-	echo "$input"
+	# Strip multiple slashes
+	echo $(echo "$input" | sed 's:/*$::')
 }
 
 function panic() {
@@ -49,7 +54,7 @@ function create_config_if_nonexistent() {
 		echo "Creating config file at: $CONFIG_FILE"
 		touch_create_parent "$CONFIG_FILE";
 	else
-		# echo "Config already exists"
+		# Config already exists
 		return 0
 	fi
 
@@ -62,6 +67,7 @@ function create_config_if_nonexistent() {
 		else
 			echo "Path to default notebook is invalid or nonexistent: $default_notebook"
 		fi
+		# shellcheck disable=SC2162
 		read -p "Enter a valid path to the root of your default notebook: " default_notebook
 	done
 
@@ -70,7 +76,7 @@ function create_config_if_nonexistent() {
 }
 
 function get_config_file_path() {
-	CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/fzf-notes/fzf-notes.conf"
+	CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/fzf-notes"
 	echo "$CONFIG_FILE"
 }
 
@@ -112,8 +118,7 @@ function get_path_for_notebook_name() {
 	target_notebook_name="$1"
 	notebooks_and_paths=$(get_notebooks_and_paths_from_config)
 	path=$(echo "$notebooks_and_paths" | grep "^$target_notebook_name:" | head -n 1 | cut -d":" -f2)
-	eval path="$(trim "$path")"
-	echo $path
+	echo "$path"
 }
 
 #####
@@ -122,7 +127,7 @@ function get_path_for_notebook_name() {
 
 function select_file_for_editing() {
 	given_file="$1"
-	fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
+	fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file" || true
 }
 
 function select_notebook_from_list() {
@@ -147,8 +152,6 @@ function select_notebook() {
 	echo "$path_to_notebook"
 }
 
-NEW_FILE_CREATION_OPTION="CREATE NEW FILE"
-
 ###############################
 # Globals:
 #   NEW_FILE_CREATION_OPTION
@@ -161,18 +164,31 @@ NEW_FILE_CREATION_OPTION="CREATE NEW FILE"
 function interact_with_notebook() {
 	path_to_notebook="$1"
 	cd "$path_to_notebook"
-	touch "$NEW_FILE_CREATION_OPTION"
+	new_file_creation_option="${globals[NEW_FILE_CREATION_OPTION]}"
+	touch "$new_file_creation_option"
 	search="$2"
 	file_to_edit=$(select_file_for_editing "$search")
+	remove_new_file_creation_option
 
-	if [ "$file_to_edit" == "$NEW_FILE_CREATION_OPTION" ]; then
+	if [ "$file_to_edit" == "$new_file_creation_option" ]; then
+		# shellcheck disable=SC2162
 		read -p "Enter a new file name: " file_to_edit
 		touch_create_parent "$file_to_edit"
+	elif [ -z "$file_to_edit" ]; then # Ctrl-c
+	    exit
 	fi
-	rm "$NEW_FILE_CREATION_OPTION"
+
 	"$EDITOR" "$file_to_edit"
 	interact_with_notebook "$path_to_notebook" ""
 }
+
+#########
+# GLOBALS
+#########
+
+declare -A globals
+globals[NEW_FILE_CREATION_OPTION]="CREATE_NEW_FILE"
+globals[curr_notebook_path]=""
 
 ######
 # Main
@@ -201,7 +217,8 @@ function main() {
 	# Handle args
 	# https://stackoverflow.com/a/29754866
 	#############
-	getopt --test > /dev/null && panic '`getopt --test` failed in this environment.'
+	# shellcheck disable=SC2016
+    getopt --test > /dev/null && panic '`getopt --test` failed in this environment.'
 
 	OPTIONS=bcChn:s:v
 	LONGOPTS=browse,config,edit-config,help,notebook:,search:,verbose
@@ -210,7 +227,7 @@ function main() {
 	# -pass arguments only via   -- "$@"   to separate them correctly
 	PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@") || panic "Something went wrong with getopt."
 
-	# read getopt’s output this way to handle the quoting right:
+	# read getopt’s output this way to handle the quoting right
 	eval set -- "$PARSED"
 
 	notebook=""
@@ -251,7 +268,7 @@ function main() {
 				break
 				;;
 			*)
-				echo "Programming error"
+				echo "An unexpected error occurred."
 				exit 3
 				;;
 		esac
@@ -266,7 +283,10 @@ function main() {
 		notebook_path="$(get_path_for_notebook_name "$notebook")"
 	fi
 
-	# Make sure notebook is in config (only necessary for -n)
+	# Trim trailing slash from notebook path
+	eval notebook_path="$(trim "$notebook_path")"
+
+	# Make sure notebook is in config (only necessary for -n, which is the else case above)
 	if [ -z "$notebook_path" ]; then
 		panic "Invalid notebook name: $notebook.";
 	fi
@@ -276,14 +296,16 @@ function main() {
 		panic "Invalid notebook path: $notebook_path"
 	fi
 
+    # Save path for deletion of NEW_FILE_CREATION_OPTION in remove_new_file_creation_option
+	globals[curr_notebook_path]="$notebook_path"
+
 	interact_with_notebook "$notebook_path" "$search";
 }
 
-# Hook signals to clean up
-trap cleanup INT TERM
-
-function cleanup () {
-	rm "$NEW_FILE_CREATION_OPTION"
+function remove_new_file_creation_option () {
+    # curr_notebook_path is guaranteed to not have a trailing slash
+    new_file_creation_option_path="${globals[curr_notebook_path]}/${globals[NEW_FILE_CREATION_OPTION]}"
+    rm -f "$new_file_creation_option_path"
 }
 
 main "$*"
