Remove NEW_FILE_CREATION file on exit

diff --git a/fzf-notes b/fzf-notes
--- a/fzf-notes
+++ b/fzf-notes
@@ -6,6 +6,8 @@
 # A script for quickly editing your notes. Allows creation of new files by
 # selecting CREATE_NEW_FILE at the menu.
 
+# Depends on GNU getopt
+
 # Exit on error
 set -e
 
@@ -52,7 +54,7 @@ function create_config_if_nonexistent() {
 		echo "Creating config file at: $CONFIG_FILE"
 		touch_create_parent "$CONFIG_FILE";
 	else
-		# echo "Config already exists"
+		# Config already exists
 		return 0
 	fi
 
@@ -65,6 +67,7 @@ function create_config_if_nonexistent() {
 		else
 			echo "Path to default notebook is invalid or nonexistent: $default_notebook"
 		fi
+		# shellcheck disable=SC2162
 		read -p "Enter a valid path to the root of your default notebook: " default_notebook
 	done
 
@@ -73,7 +76,7 @@ function create_config_if_nonexistent() {
 }
 
 function get_config_file_path() {
-	CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/fzf-notes/fzf-notes.conf"
+	CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/fzf-notes"
 	echo "$CONFIG_FILE"
 }
 
@@ -115,8 +118,7 @@ function get_path_for_notebook_name() {
 	target_notebook_name="$1"
 	notebooks_and_paths=$(get_notebooks_and_paths_from_config)
 	path=$(echo "$notebooks_and_paths" | grep "^$target_notebook_name:" | head -n 1 | cut -d":" -f2)
-	eval path="$(trim "$path")"
-	echo $path
+	echo "$path"
 }
 
 #####
@@ -125,7 +127,7 @@ function get_path_for_notebook_name() {
 
 function select_file_for_editing() {
 	given_file="$1"
-	fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
+	fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file" || true
 }
 
 function select_notebook_from_list() {
@@ -162,15 +164,20 @@ function select_notebook() {
 function interact_with_notebook() {
 	path_to_notebook="$1"
 	cd "$path_to_notebook"
-	touch "$NEW_FILE_CREATION_OPTION"
+	new_file_creation_option="${globals[NEW_FILE_CREATION_OPTION]}"
+	touch "$new_file_creation_option"
 	search="$2"
 	file_to_edit=$(select_file_for_editing "$search")
+	remove_new_file_creation_option
 
-	if [ "$file_to_edit" == "${globals[NEW_FILE_CREATION_OPTION]}" ]; then
+	if [ "$file_to_edit" == "$new_file_creation_option" ]; then
+		# shellcheck disable=SC2162
 		read -p "Enter a new file name: " file_to_edit
 		touch_create_parent "$file_to_edit"
+	elif [ -z "$file_to_edit" ]; then # Ctrl-c
+	    exit
 	fi
-	rm "$NEW_FILE_CREATION_OPTION"
+
 	"$EDITOR" "$file_to_edit"
 	interact_with_notebook "$path_to_notebook" ""
 }
@@ -210,7 +217,8 @@ function main() {
 	# Handle args
 	# https://stackoverflow.com/a/29754866
 	#############
-	getopt --test > /dev/null && panic '`getopt --test` failed in this environment.'
+	# shellcheck disable=SC2016
+    getopt --test > /dev/null && panic '`getopt --test` failed in this environment.'
 
 	OPTIONS=bcChn:s:v
 	LONGOPTS=browse,config,edit-config,help,notebook:,search:,verbose
@@ -219,7 +227,7 @@ function main() {
 	# -pass arguments only via   -- "$@"   to separate them correctly
 	PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@") || panic "Something went wrong with getopt."
 
-	# read getopt’s output this way to handle the quoting right:
+	# read getopt’s output this way to handle the quoting right
 	eval set -- "$PARSED"
 
 	notebook=""
@@ -260,7 +268,7 @@ function main() {
 				break
 				;;
 			*)
-				echo "Programming error"
+				echo "An unexpected error occurred."
 				exit 3
 				;;
 		esac
@@ -275,7 +283,10 @@ function main() {
 		notebook_path="$(get_path_for_notebook_name "$notebook")"
 	fi
 
-	# Make sure notebook is in config (only necessary for -n)
+	# Trim trailing slash from notebook path
+	eval notebook_path="$(trim "$notebook_path")"
+
+	# Make sure notebook is in config (only necessary for -n, which is the else case above)
 	if [ -z "$notebook_path" ]; then
 		panic "Invalid notebook name: $notebook.";
 	fi
@@ -285,18 +296,16 @@ function main() {
 		panic "Invalid notebook path: $notebook_path"
 	fi
 
-    # Save path for deletion of NEW_FILE_CREATION_OPTION in cleanup
+    # Save path for deletion of NEW_FILE_CREATION_OPTION in remove_new_file_creation_option
 	globals[curr_notebook_path]="$notebook_path"
 
 	interact_with_notebook "$notebook_path" "$search";
 }
 
-# Hook signals to clean up
-trap cleanup INT TERM
-
-function cleanup () {
-    # TODO: Make sure that the curr_notebook_path doesn't have a slash at the end already
-	rm "${globals[curr_notebook_path]}/${globals[NEW_FILE_CREATION_OPTION]}"
+function remove_new_file_creation_option () {
+    # curr_notebook_path is guaranteed to not have a trailing slash
+    new_file_creation_option_path="${globals[curr_notebook_path]}/${globals[NEW_FILE_CREATION_OPTION]}"
+    rm -f "$new_file_creation_option_path"
 }
 
 main "$*"
