Add command line options

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -1,163 +1,106 @@
 #!/usr/bin/env bash
 # Modified from https://gist.github.com/BaseCase/c45299e4f8474119881d708a4b728fbf
-# by Aaron Lichtman -- https://github.com/alichtman
+# by Aaron Lichtman -- https://github.com/alichtman/fzf-notes
 
-# notes.sh
-#
 # A script for quickly editing your notes. Allows creation of new files by
-# selecting CREATE_NEW_FILE at the menu. Depends on the $NOTES env var
-# being set.
+# selecting CREATE_NEW_FILE at the menu.
 
-# Exit upon failure.
+# Exit upon error (make bash pretend to be more like a real programming language)
 set -e
-
-################
-# Color Printing
-################
-
-# The following function prints a text using custom color
-# -c or --color define the color for the print. See the array colors for the available options.
-# -n or --noline directs the system not to print a new line after the content.
-# Last argument is the message to be printed.
-# https://bytefreaks.net/gnulinux/bash/cecho-a-function-to-print-using-different-colors-in-bash
-cecho () {
-    declare -A colors;
-    colors=(\
-        ['black']='\E[0;47m'\
-        ['red']='\E[0;31m'\
-        ['green']='\E[0;32m'\
-        ['yellow']='\E[0;33m'\
-        ['blue']='\E[0;34m'\
-        ['magenta']='\E[0;35m'\
-        ['cyan']='\E[0;36m'\
-        ['white']='\E[0;37m'\
-    );
- 
-    local defaultMSG="No message passed.";
-    local defaultColor="black";
-    local defaultNewLine=true;
- 
-    while [[ $# -gt 1 ]];
-    do
-    key="$1";
- 
-    case $key in
-        -c|--color)
-            color="$2";
-            shift;
-        ;;
-        -n|--noline)
-            newLine=false;
-        ;;
-        *)
-            # unknown option
-        ;;
-    esac
-    shift;
-    done
- 
-    message=${1:-$defaultMSG};   # Defaults to default message.
-    color=${color:-$defaultColor};   # Defaults to default color, if not specified.
-    newLine=${newLine:-$defaultNewLine};
- 
-    echo -en "${colors[$color]}";
-    echo -en "$message";
-    if [ "$newLine" = true ] ; then
-        echo;
-    fi
-    tput sgr0; #  Reset text attributes to normal without clearing screen.
- 
-    return;
-}
- 
-function warning() {
-    cecho -c 'yellow' "$@";
-}
- 
-function error() {
-    cecho -c 'red' "$@";
-}
- 
-function information() {
-    cecho -c 'blue' "$@";
-}
 
 #########
 # Helpers
 #########
 
+function get_version() {
+	echo "fzf-notes v0.1"
+}
+
 function touch_create_parent() {
-    mkdir -p "$(dirname "$1")" && touch "$1"
+	mkdir -p "$(dirname "$1")" && touch "$1"
 }
 
 # Trims leading and trailing whitespace from argument
 function trim() {
-    shopt -s extglob
-    input="$1"
-    input="${input##*( )}"
-    input="${input%%*( )}"
-    shopt -u extglob
-    echo "$input"
+	shopt -s extglob
+	input="$1"
+	input="${input##*( )}"
+	input="${input%%*( )}"
+	shopt -u extglob
+	echo "$input"
 }
 
-
+function panic() {
+	echo "ERROR: $1"
+	exit 1;
+}
 
 ########
 # Config
 ########
 
 function create_config_if_nonexistent() {
-    CONFIG_FILE=$(get_config_file_path);
-    if [ ! -f "$CONFIG_FILE" ];
-    then
-        information "Creating config file at: $CONFIG_FILE"
-        touch_create_parent "$CONFIG_FILE";
-    else
-        warning "Config already exists"
-        return
-    fi
+	CONFIG_FILE=$(get_config_file_path);
+	if [ ! -f "$CONFIG_FILE" ];
+	then
+		echo "Creating config file at: $CONFIG_FILE"
+		touch_create_parent "$CONFIG_FILE";
+	else
+		# echo "Config already exists"
+		return 0
+	fi
 
-    default_notebook=""
-    while [ ! -d "$default_notebook" ]
-    do
-        if [ -z "$default_notebook" ]; then
-            warning "Default notebook is unset."
-        else
-            warning "Path to default notebook is invalid or nonexistent: $default_notebook"
-        fi
-        read -p "Enter a valid path to the root of your default notebook: " default_notebook
-    done
+	default_notebook=""
+	while [ ! -d "$default_notebook" ]
+	do
+		if [ -z "$default_notebook" ]; then
+			echo "Default notebook is unset."
+		else
+			echo "Path to default notebook is invalid or nonexistent: $default_notebook"
+		fi
+		read -p "Enter a valid path to the root of your default notebook: " default_notebook
+	done
 
-    information "Setting default notebook to $default_notebook"
-    yq n notebooks.default "$default_notebook" > "$CONFIG_FILE"
+	echo "Setting default notebook to $default_notebook"
+	yq n notebooks.default "$default_notebook" > "$CONFIG_FILE"
 }
 
 function get_config_file_path() {
-    CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/fzf-notes/fzf-notes.conf"
-    echo "$CONFIG_FILE"
+	CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/fzf-notes/fzf-notes.conf"
+	echo "$CONFIG_FILE"
 }
 
 ###########
 # Notebooks
 ###########
 
+# Returns lines in form of "name": "path"
 function get_notebooks_and_paths_from_config() {
-    CONFIG_FILE=$(get_config_file_path);
-    yq r "$CONFIG_FILE" notebooks
+	CONFIG_FILE=$(get_config_file_path);
+	yq r "$CONFIG_FILE" notebooks
 }
 
-# Takes list of lines in format of "notebooks: path" and returns only the notebooks
+# Takes list of lines in format of "notebooks: path" and returns only
+# the notebook names
 function get_notebook_names() {
-    notebooks_and_paths="$1"
-    echo "$notebooks_and_paths" | cut -d":" -f1
+	notebooks_and_paths="$1"
+	echo "$notebooks_and_paths" | cut -d":" -f1
 }
 
-# YAML config file and selected notebook name passed in. Path to notebook returned.
+#######################################
+# Looks up path of notebook by its name.
+# Globals:
+# 	None
+# Arguments:
+#   $1 -> Target notebook name
+# Returns:
+#   Path to notebook if name is valid, "" otherwise
+#######################################
 function get_path_for_notebook_name() {
-    notebooks_and_paths="$1"
-    target_notebook_name="$2"
-    path=$(echo "$notebooks_and_paths" | grep "^$target_notebook_name:" | cut -d":" -f2)
-    trim "$path"
+	target_notebook_name="$1"
+	notebooks_and_paths=$(get_notebooks_and_paths_from_config)
+	path=$(echo "$notebooks_and_paths" | grep "^$target_notebook_name:" | cut -d":" -f2)
+	trim "$path"
 }
 
 #####
@@ -165,13 +108,23 @@ function get_path_for_notebook_name() {
 #####
 
 function select_file_for_editing() {
-    given_file="$1"
-    fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
+	given_file="$1"
+	fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
 }
 
-function select_notebook() {
-    notebooks="$1"
-    echo "$notebooks" | fzf
+function select_notebook_from_list() {
+	notebooks="$1"
+	echo "$notebooks" | fzf
+}
+
+# Select notebook from list of notebooks
+function select_notebook () {
+	notebooks_and_paths=$(get_notebooks_and_paths_from_config);
+	notebooks=$(get_notebook_names "$notebooks_and_paths");
+	selected_notebook=$(select_notebook_from_list "$notebooks");
+	echo "Selected: $selected_notebook"
+	path_to_notebook=$(get_path_for_notebook_name "$selected_notebook");
+	echo "Path to notebook: $path_to_notebook"
 }
 
 ######
@@ -180,40 +133,141 @@ function select_notebook() {
 
 new_file_creation_option="CREATE_NEW_FILE"
 
+###############################
+# Globals:
+# 	None
+# Arguments:
+#   $1 -> Path to notebook root
+#   $2 -> File name search
+# Returns:
+#   None
+################################
+function interact_with_notebook() {
+	$path_to_notebook="$1"
+	cd "$path_to_notebook"
+	touch "$new_file_creation_option"
+	search="$2"
+	file_to_edit=$(select_file_for_editing "$search")
+
+	if [ -n "$file_to_edit" ] ; then
+	  if [ "$file_to_edit" == "$new_file_creation_option" ] ; then
+		  read -p "Enter a new file name: " file_to_edit
+		  touch_create_parent "$file_to_edit"
+	  fi
+	rm "$new_file_creation_option"
+	"$EDITOR" "$file_to_edit"
+	interact_with_notebook "$path_to_notebook" ""
+	fi
+	cd -
+}
+
+function show_help() {
+	echo "$(basename "$0") [-h] [-b] [-c] [-n] -- Notetaking integrated with fzf.
+
+  where:
+  	-b  browse notebooks
+  	-c  show config file path
+  	-h  show this help text
+  	-n  open notebook by name
+  	-s  search for file in notebook."
+}
+
 function main() {
-    # Make sure config exists
-    create_config_if_nonexistent;
+	# Make sure config exists
+	create_config_if_nonexistent;
 
-    # Select notebook from list of notebooks
-    notebooks_and_paths=$(get_notebooks_and_paths_from_config);
-    notebooks=$(get_notebook_names "$notebooks_and_paths");
-    selected_notebook=$(select_notebook "$notebooks");
-    error "Selected: $selected_notebook"
-    path_to_notebook=$(get_path_for_notebook_name "$notebooks_and_paths" "$selected_notebook");
-    error "Path to notebook: $path_to_notebook"
+	#############
+	# Handle args
+	# https://stackoverflow.com/a/29754866
+	#############
 
-    cd "$path_to_notebook"
-    touch "$new_file_creation_option"
-    previous_file="$1"
-    file_to_edit=$(select_file_for_editing "$previous_file")
+	# -allow a command to fail with !’s side effect on errexit
+	# -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+	! getopt --test > /dev/null
+	if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
+		panic '`getopt --test` failed in this environment.'
+	fi
 
-    if [ -n "$file_to_edit" ] ; then
-      if [ "$file_to_edit" == "$new_file_creation_option" ] ; then
-          read -p "Enter a new file name: " file_to_edit
-          touch_create_parent "$file_to_edit"
-      fi
-    rm "$new_file_creation_option"
-    "$EDITOR" "$file_to_edit"
-    main "$file_to_edit"
-    fi
-    cd -
+	OPTIONS=bchn:v
+	LONGOPTS=browse,config,help,notebook:,verbose
+	# -regarding ! and PIPESTATUS see above
+	# -temporarily store output to be able to check for errors
+	# -activate quoting/enhanced mode (e.g. by writing out “--options”)
+	# -pass arguments only via   -- "$@"   to separate them correctly
+	! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+	if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+		panic "Something went wrong with getopt."
+	fi
+
+	# read getopt’s output this way to handle the quoting right:
+	eval set -- "$PARSED"
+
+	notebook=""
+	browse=false
+	while true; do
+		case "$1" in
+			-b|--browse)
+				browse=true
+				shift
+				;;
+			-c|--config)
+				get_config_file_path;
+				exit 0
+				;;
+			-h|--help)
+				show_help;
+				exit 0
+				;;
+			-v|--version)
+				get_version;
+				exit 0
+				;;
+			-n|--notebook)
+				notebook=$(trim "$2")
+				shift 2
+				;;
+			--)
+				shift
+				break
+				;;
+			*)
+				echo "Programming error"
+				exit 3
+				;;
+		esac
+	done
+
+	# If notebook wasn't set by -n flag and -b flag passed, show the
+	# interactive notebook selector. Otherwise, set notebook to default
+	if [[ "$browse" == true && -z "$notebook" ]]; then
+		notebook=$(select_notebook)
+	else
+		notebook="default"
+	fi
+
+	notebook_path="$(get_path_for_notebook_name "$notebook")"
+	# Make sure notebook is in config (only necessary for -n)
+	if [ -n "$notebook_path" ]; then
+		panic "Invalid notebook name: $notebook.";
+	fi
+
+	# Make sure notebook path exists
+	if [ ! -d "$notebook_path" ]; then
+		panic "Invalid notebook path: $notebook_path"
+	fi
+
+	#
+	interact_with_notebook "$notebook_path";
+
+	# TODO: Fix looping
+	# TODO: Add -s search flag
 }
 
 # Hook signals to clean up
 trap cleanup INT TERM
 
 function cleanup () {
-    rm "$new_file_creation_option"
+	rm "$new_file_creation_option"
 }
 
 main "$*"
